spring:
  application:
    name: wms-practice


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wms_warehouse
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      connect-timeout: 3s
      timeout: 3s

jwt:
  secret: "8Rq+y1v2aWJr8DdJWtnXKQ6m/3ojMJAi5noaj2yXWOw="
  expiration: 14400000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

